[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 999999
via_ir = false
solc = "0.8.26"
evm_version = "cancun"
verbosity = 2
ffi = true
fuzz.runs = 10000

fs_permissions = [
  {access = "read", path = "test/bin"}
]

remappings = [
  "forge-std=lib/forge-std/src",
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
  "@aave=lib/aave-v3-core/contracts",
  "@chainlink=lib/foundry-chainlink-toolkit/src"
]

[profile.coverage.fuzz]
runs = 100

[profile.intense.fuzz]
runs = 100000
max_test_rejects = 999999

[fmt]
line_length = 160
number_underscore = "thousands"

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
goerli = "https://goerli.infura.io/v3/${INFURA_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"
polygon_pos = "https://polygon-mainnet.infura.io/v3/${INFURA_KEY}"
mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_KEY}"
polygon_zkevm = "https://zkevm-rpc.com"
polygon_zkevm_testnet = "https://rpc.public.zkevm-test.net"
base = " https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
polygon_pos = { key = "${POLYGONSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}" }
polygon_zkevm = { key = "${POLYGONSCAN_ZKEVM_API_KEY}" }
polygon_zkevm_testnet = { key = "${POLYGONSCAN_ZKEVM_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config