// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

////////////////////////////////////////////////////
// AUTOGENERATED - DO NOT EDIT THIS FILE DIRECTLY //
////////////////////////////////////////////////////

import "forge-std/Script.sol";

import "script/mocks/USDC.sol";

abstract contract USDCDeployer is Script {

    function deployUSDC() internal returns (address usdc) {
        vm.startBroadcast(vm.envUint("PRIVATE_KEY"));
        usdc = address(new USDC());
        vm.stopBroadcast();
    }
}
